// DefTable to XML convertor script
// ver 1 (created 2013/08/05, 03:51)
// by "StaticZ" <staticz@uoquint.ru>

using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace CentrEd_plus
{
    class def2xml
    {
        private static StreamWriter wr;
        private static string   folder;

        private static void ParseDefTable(string name, int idxstart, int idxcount, int idxview)
        {
            Console.WriteLine("Parsing file: \"{0}.txt\"...", name);
            var tr = new StreamReader(Path.Combine(folder, name+".txt"));
            string[] types = null, names = null;
            wr.WriteLine("\t<Category Name=\"{0}\">", name);

            while (!tr.EndOfStream) {
                var st = tr.ReadLine();
                if (String.IsNullOrWhiteSpace(st))
                    continue;
                var value = st.Split(new [] { '\t' }, StringSplitOptions.RemoveEmptyEntries);
                if (types == null) {
                    types = value.Select(s => s.ToLower()).ToArray();
                    continue;
                }
                if (names == null) {
                    names = value;
                    continue;
                }
                wr.WriteLine("\t\t<Material Name=\"{0}\" TileID=\"0x{1:X4}\">", value.Last(), 0x4000 + Int32.Parse(value[idxstart + idxview]));
                for (int i = idxstart; i < idxstart+idxcount; ++i)
                    if (types[i]!="int")
                        throw new FormatException("Unknown data file format: "+name+".txt");
                    else if (value[i] != "0")
                        wr.WriteLine("\t\t\t<Item ID=\"0x{1:X4}\" Type=\"{0}\" />", names[i], Int32.Parse(value[i], NumberStyles.Integer));
                wr.WriteLine("\t\t</Material>");
            }
            wr.WriteLine("\t</Category>");
            tr.Close();
            tr.Dispose();
        }

        static void Main(string[] args)
        {
            if (args.Length != 1) {
                Console.WriteLine("Usage: {0} path\n\tpath - path to folder with this files: \"roof.txt\", \"walls.txt\", \"floors.txt\", \"stairs.txt\", \"misc.txt\"", Path.GetFileName(Environment.GetCommandLineArgs()[0]));
                return;
            }

            folder = args[0];
            wr = new StreamWriter("MaterialInf.xml", false, Encoding.UTF8);
            wr.WriteLine("<?xml version=\"1.0\" ?>");
            wr.WriteLine("<MaterialInf Version=\"0 ({0})\" Author=\"Generated by def2xml convertor script\">", DateTime.UtcNow.ToString("dd.MM.yyyy"));

            ParseDefTable("Roof",   3, 16, 1);
            ParseDefTable("Walls",  3, 14, 4);
            ParseDefTable("Floors", 1, 16, 1);
            ParseDefTable("Stairs", 1, 13, 2);
            ParseDefTable("Misc",   3,  8, 1);

            wr.WriteLine("</MaterialInf>");  
            wr.Flush();
            wr.Close();
            Console.WriteLine("Parsing all files complete successfully");
        }
    }
}
