/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OutHouse3Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OutHouse3AddonDeed();
			}
		}

		[ Constructable ]
		public OutHouse3Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 421 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 422 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 423 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 427 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 425 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 425 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1116 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 1, 0, 23 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 9947 );
			AddComponent( ac, 1, 2, 23 );
			ac = new AddonComponent( 9948 );
			AddComponent( ac, 0, 0, 23 );
			ac = new AddonComponent( 9948 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 9948 );
			AddComponent( ac, 0, 2, 23 );
			ac = new AddonComponent( 9407 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -1, 2, 2 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 0, 2, 2 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, 2, 2 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 2, 2, 2 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 3203 );
			AddComponent( ac, 2, -1, 2 );
			ac = new AddonComponent( 1759 );
			AddComponent( ac, 1, 0, 0 );

		}

		public OutHouse3Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OutHouse3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OutHouse3Addon();
			}
		}

		[Constructable]
		public OutHouse3AddonDeed()
		{
			Name = "OutHouse3";
		}

		public OutHouse3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}