/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OutHouse2Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OutHouse2AddonDeed();
			}
		}

		[ Constructable ]
		public OutHouse2Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 10082 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 10079 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1114 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 4781 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 10076 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 9154 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 9156 );
			AddComponent( ac, 2, 1, 20 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 9158 );
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 9160 );
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 9162 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 9164 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 9166 );
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 9168 );
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 9165 );
			AddComponent( ac, 1, 0, 23 );
			ac = new AddonComponent( 9163 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 9161 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 9167 );
			AddComponent( ac, 0, 0, 23 );

		}

		public OutHouse2Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OutHouse2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OutHouse2Addon();
			}
		}

		[Constructable]
		public OutHouse2AddonDeed()
		{
			Name = "OutHouse2";
		}

		public OutHouse2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}