/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OutHouse5Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OutHouse5AddonDeed();
			}
		}

		[ Constructable ]
		public OutHouse5Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, -1, 1, 23 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 2, 1, 23 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, 3, 1, 23 );
			ac = new AddonComponent( 3233 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 54 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, -2, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, -2, -1, 21 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 1533 );
			AddComponent( ac, -2, 1, 23 );
			ac = new AddonComponent( 3233 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 52 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 53 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1115 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1115 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, -1, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 0, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 1, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 2, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 3, 0, 24 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, -1, -1, 21 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 0, -1, 21 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 1, -1, 21 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 2, -1, 21 );
			ac = new AddonComponent( 1534 );
			AddComponent( ac, 3, -1, 21 );
			ac = new AddonComponent( 3233 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3259 );
			AddComponent( ac, 3, 0, 0 );

		}

		public OutHouse5Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OutHouse5AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OutHouse5Addon();
			}
		}

		[Constructable]
		public OutHouse5AddonDeed()
		{
			Name = "OutHouse5";
		}

		public OutHouse5AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}