/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OutHouse1Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OutHouse1AddonDeed();
			}
		}

		[ Constructable ]
		public OutHouse1Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, 2, 0, 1 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 15871 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 15871 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 28 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 3, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -1, 1, 23 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 2, 1, 23 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, 3, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -1, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -1, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 0, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 1, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 2, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 2, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 3, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 3, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -1, 0, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 0, 0, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 2, 0, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, 3, -1, 20 );
			ac = new AddonComponent( 1701 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3272 );
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 3272 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3237 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 3, 0, 1 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, 3, 1, 1 );
			ac = new AddonComponent( 1701 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, -2, 0, 1 );
			ac = new AddonComponent( 27 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 29 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 6458 );
			AddComponent( ac, -2, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, 0, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, 1, 23 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, -1, 20 );
			ac = new AddonComponent( 6460 );
			AddComponent( ac, -2, 0, 20 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, -2, 1, 1 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 2581 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 2, 10 );

		}

		public OutHouse1Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OutHouse1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OutHouse1Addon();
			}
		}

		[Constructable]
		public OutHouse1AddonDeed()
		{
			Name = "OutHouse1";
		}

		public OutHouse1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}