/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OutHouseAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OutHouseAddonDeed();
			}
		}

		[ Constructable ]
		public OutHouseAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 7 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 7 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 7 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 7 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 8 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 8 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 8 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -2, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 0, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 1, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 2, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -2, 1, 23 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -1, 1, 23 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 0, 1, 23 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 1, 1, 23 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, 2, 1, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -2, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -1, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 0, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 1, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 2, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -2, -1, 20 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -1, -1, 20 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 0, -1, 20 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, 2, -1, 20 );
			ac = new AddonComponent( 3476 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 3478 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, 1, 2, 1 );
			ac = new AddonComponent( 3233 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 3237 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 13001 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 8 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 8 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -3, 2, 20 );
			ac = new AddonComponent( 8685 );
			AddComponent( ac, -3, 1, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -3, 0, 23 );
			ac = new AddonComponent( 8687 );
			AddComponent( ac, -3, -1, 20 );
			ac = new AddonComponent( 3204 );
			AddComponent( ac, -3, 2, 1 );
			ac = new AddonComponent( 3206 );
			AddComponent( ac, -3, 1, 1 );

		}

		public OutHouseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OutHouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OutHouseAddon();
			}
		}

		[Constructable]
		public OutHouseAddonDeed()
		{
			Name = "OutHouse";
		}

		public OutHouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}