
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PearlDiverHutAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1217, -2, 2, 7}, {1217, -2, -2, 7}, {1217, -2, -1, 7}// 1	2	3	
			, {1217, -2, 0, 7}, {1217, -2, 1, 7}, {432, -3, 0, 7}// 4	5	6	
			, {424, -3, -3, 7}, {422, -2, -3, 7}, {426, -3, 2, 7}// 8	9	10	
			, {425, -3, -2, 7}, {425, -3, -1, 7}, {425, -3, 1, 7}// 11	12	13	
			, {422, -2, 2, 7}, {4567, -2, -1, 7}, {4566, -2, 1, 7}// 14	15	16	
			, {4568, -2, 0, 7}, {1425, -2, -2, 27}, {1425, -2, -1, 27}// 17	20	21	
			, {1425, -2, 0, 27}, {1425, -2, 1, 27}, {1425, -2, 2, 27}// 22	23	24	
			, {1425, -2, 3, 27}, {3239, -3, 3, 0}, {3257, -2, 3, 0}// 25	26	27	
			, {1217, -1, 2, 7}, {1218, 0, 2, 7}, {1217, 1, 2, 7}// 28	29	30	
			, {1217, 2, 2, 7}, {1217, 2, 1, 7}, {1217, 2, 0, 7}// 31	32	33	
			, {1217, 2, -1, 7}, {1217, 2, -2, 7}, {1217, 1, -2, 7}// 34	35	36	
			, {1217, 0, -2, 7}, {1217, -1, -2, 7}, {1217, -1, 1, 7}// 37	38	39	
			, {1217, -1, 0, 7}, {1217, -1, -1, 7}, {1217, 0, -1, 7}// 40	41	42	
			, {1217, 1, -1, 7}, {1217, 1, 0, 7}, {1217, 1, 1, 7}// 43	44	45	
			, {1217, 0, 1, 7}, {1217, 0, 0, 7}, {421, 2, 2, 7}// 46	47	48	
			, {423, 2, -3, 7}, {431, 2, 0, 7}, {422, 1, -3, 7}// 49	50	59	
			, {422, -1, -3, 7}, {425, 2, 1, 7}, {425, 2, -1, 7}// 60	61	62	
			, {425, 2, -2, 7}, {422, -1, 2, 7}, {422, 1, 2, 7}// 63	64	65	
			, {4604, -1, 0, 7}, {4605, 0, -2, 7}, {4606, 1, -2, 7}// 66	68	69	
			, {8539, 1, 2, 27}, {8539, 0, 2, 27}, {8539, -1, 2, 27}// 70	71	72	
			, {1415, 3, 2, 27}, {1415, 3, 1, 27}, {1415, 3, 0, 27}// 73	74	75	
			, {1415, 3, -1, 27}, {1415, 3, -2, 27}, {1415, 3, 3, 27}// 76	77	78	
			, {1423, 2, 3, 30}, {1423, 2, 2, 30}, {1423, 2, 1, 30}// 79	80	81	
			, {1423, 2, 0, 30}, {1423, 2, -1, 30}, {1423, 2, -2, 30}// 82	83	84	
			, {1423, 1, 3, 33}, {1423, 1, 2, 33}, {1423, 1, 1, 33}// 85	86	87	
			, {1423, 1, 0, 33}, {1423, 1, -1, 33}, {1423, 1, -2, 33}// 88	89	90	
			, {1425, -1, -2, 30}, {1425, -1, -1, 30}, {1425, -1, 0, 30}// 91	92	93	
			, {1425, -1, 1, 30}, {1425, -1, 2, 30}, {1425, -1, 3, 30}// 94	95	96	
			, {1425, 0, 3, 33}, {1425, 0, 2, 33}, {1425, 0, 1, 33}// 97	98	99	
			, {1425, 0, 0, 33}, {1425, 0, -1, 33}, {1425, 0, -2, 33}// 100	101	102	
			, {430, 0, -3, 7}, {3244, 3, -2, 0}, {3247, 3, 1, 0}// 103	104	105	
			, {3248, 1, 3, 0}, {3258, 3, 0, 0}, {3270, 2, 3, 0}// 106	107	108	
			, {3237, 3, 3, 0}, {3241, 3, -1, 0}, {3269, 1, 3, 0}// 109	110	111	
			, {3261, 3, -2, 0}, {3260, -1, 3, 0}// 112	113	
		};

 
        private static int[,] m_AddOnComplexComponents = new int[,] {
			  {1848, -2, 2, 2, 1001, -1 }, {1848, -1, 2, 2, 1001, -1 }, {1848, 0, 2, 2, 1001, -1 }// 7	51	52	
			, {1848, 1, 2, 2, 1001, -1 }, {1848, 2, 2, 2, 1001, -1 }, {1848, 2, 1, 2, 1001, -1 }// 53	54	55	
			, {1848, 2, 0, 2, 1001, -1 }, {1848, 2, -1, 2, 1001, -1 }, {1848, 2, -2, 2, 1001, -1 }// 56	57	58	
			, {1849, 0, 3, 0, 1001, -1 }// 67	
		};

    
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PearlDiverHutAddonDeed();
			}
		}

		[ Constructable ]
		public PearlDiverHutAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );

            for (int i = 0; i < m_AddOnComplexComponents.Length / 6; i++)
                AddComplexComponent( (BaseAddon)this, m_AddOnComplexComponents[i,0], m_AddOnComplexComponents[i,1], m_AddOnComplexComponents[i,2], m_AddOnComplexComponents[i,3], m_AddOnComplexComponents[i,4], m_AddOnComplexComponents[i,5] );

			AddComplexComponent( (BaseAddon) this, 11554, -2, 0, 13, 1153, -1, "Pearl Knife" );// 18
			AddComplexComponent( (BaseAddon) this, 3826, -2, -2, 7, 1150, -1, "White Pearls" );// 19

		}

		public PearlDiverHutAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PearlDiverHutAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PearlDiverHutAddon();
			}
		}

		[Constructable]
		public PearlDiverHutAddonDeed()
		{
			Name = "PearlDiverHut";
		}

		public PearlDiverHutAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}