/////////////////////////////////////
//**Generated by Ryan**//
/////////////////////////////////////
using System;
using Server;

namespace Server.Items
{
	public class NoxLegs : LeatherLegs
	{
	 	public override int ArtifactRarity{ get{ return 10; } }
	 	public override int InitMinHits{ get{ return Utility.RandomMinMax(100, 125); } }
	 	public override int InitMaxHits{ get{ return Utility.RandomMinMax(126, 150); } }

	 	[Constructable]
	 	public NoxLegs()
	 	{
	 	 	Name = "Legs of the Swamp Queen";
	 	 	Hue = 1272;
	 	 	ArmorAttributes.MageArmor = 1;
            ArmorAttributes.SelfRepair = 5;
            PhysicalBonus = 10;
            PoisonBonus = 10;
            EnergyBonus = 10;
            ColdBonus = 10;
			FireBonus = 10;
			Attributes.Luck = 100;
			Attributes.NightSight = 1;
			Attributes.RegenHits = 2;
			Attributes.RegenMana = 2;
			Attributes.SpellDamage = 5;
	 	}

	 	public NoxLegs(Serial serial) : base( serial )
	 	{
	 	}
	 	public override void Serialize( GenericWriter writer )
	 	{
	 	 	base.Serialize( writer );

	 	 	writer.Write( (int) 0 );
	 	}
	 	public override void Deserialize(GenericReader reader)
	 	{
	 	 	base.Deserialize( reader );

	 	 	int version = reader.ReadInt();
	 	}
	}
}
