
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CoffinGlasstopbonesSouthAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CoffinGlasstopbonesSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CoffinGlasstopbonesSouthAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1981, 2, 1, 0, 1107, -1, "coffin", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1981, 1, 1, 0, 1107, -1, "coffin", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1981, 0, 1, 0, 1107, -1, "coffin", 1);// 3
			AddComplexComponent( (BaseAddon) this, 11718, 2, 0, 2, 1107, -1, "coffin", 1);// 4
			AddComplexComponent( (BaseAddon) this, 11718, 2, 1, 2, 1107, -1, "coffin", 1);// 5
			AddComplexComponent( (BaseAddon) this, 11718, -1, 0, 2, 1107, -1, "coffin", 1);// 6
			AddComplexComponent( (BaseAddon) this, 11718, -1, 1, 2, 1107, -1, "coffin", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2254, 2, 0, 2, 1102, -1, "coffin", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2254, 1, 0, 2, 1102, -1, "coffin", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2254, 0, 0, 2, 1102, -1, "coffin", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2253, 2, 1, 2, 1102, -1, "coffin", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2254, 1, 1, 2, 1102, -1, "coffin", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2254, 0, 1, 2, 1102, -1, "coffin", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2252, -1, 1, 2, 1102, -1, "coffin", 1);// 14
			AddComplexComponent( (BaseAddon) this, 924, 2, 1, 7, 1107, -1, "coffin", 1);// 15
			AddComplexComponent( (BaseAddon) this, 925, 2, 0, 7, 1107, -1, "coffin", 1);// 16
			AddComplexComponent( (BaseAddon) this, 925, 1, 0, 7, 1107, -1, "coffin", 1);// 17
			AddComplexComponent( (BaseAddon) this, 925, 1, 1, 7, 1107, -1, "coffin", 1);// 18
			AddComplexComponent( (BaseAddon) this, 925, 0, 0, 7, 1107, -1, "coffin", 1);// 19
			AddComplexComponent( (BaseAddon) this, 925, 0, 1, 7, 1107, -1, "coffin", 1);// 20
			AddComplexComponent( (BaseAddon) this, 926, -1, 1, 7, 1107, -1, "coffin", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2253, 2, 1, 9, 1102, -1, "coffin", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2254, 2, 0, 9, 1102, -1, "coffin", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2254, 1, 0, 9, 1102, -1, "coffin", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2254, 1, 1, 9, 1102, -1, "coffin", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2254, 0, 0, 9, 1102, -1, "coffin", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2254, 0, 1, 9, 1102, -1, "coffin", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2252, -1, 1, 9, 1102, -1, "coffin", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2251, -1, 0, 9, 1102, -1, "coffin", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3786, 0, 1, 2, 0, -1, "bones", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3787, 1, 1, 2, 0, -1, "bones", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3788, 2, 1, 1, 0, -1, "coffin", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3789, 1, 1, 4, 0, -1, "bones", 1);// 33
			AddComplexComponent( (BaseAddon) this, 3790, 1, 1, 2, 0, -1, "bones", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3786, 2, 1, 3, 0, -1, "coffin", 1);// 35
			AddComplexComponent( (BaseAddon) this, 3787, 1, 1, 3, 0, -1, "bones", 1);// 36
			AddComplexComponent( (BaseAddon) this, 3788, 1, 1, 2, 0, -1, "coffin", 1);// 37
			AddComplexComponent( (BaseAddon) this, 3789, 2, 1, 3, 0, -1, "bones", 1);// 38
			AddComplexComponent( (BaseAddon) this, 3790, 0, 1, 2, 0, -1, "bones", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2594, 1, 1, 3, 0, 1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 7388, 2, 1, 10, 1150, -1, "Coffin", 1);// 41
			AddComplexComponent( (BaseAddon) this, 7388, 1, 1, 10, 1150, -1, "Coffin", 1);// 42
			AddComplexComponent( (BaseAddon) this, 7388, 0, 1, 10, 1150, -1, "Coffin", 1);// 43

		}

		public CoffinGlasstopbonesSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CoffinGlasstopbonesSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CoffinGlasstopbonesSouthAddon();
			}
		}

		[Constructable]
		public CoffinGlasstopbonesSouthAddonDeed()
		{
			Name = "CoffinGlasstopbonesSouth";
		}

		public CoffinGlasstopbonesSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}