
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class hex_StovebigSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7137, -1, 1, 5}, {3134, 2, 1, 12}, {2541, -1, 1, 12}// 1	8	9	
			, {7137, 0, 1, 5}, {2880, 1, 1, 1}, {7137, -2, 1, 0}// 11	12	13	
			, {2880, 2, 1, 1}, {2416, -1, 1, 18}, {7827, 1, 1, 16}// 14	25	27	
			, {2449, 1, 1, 7}, {2423, 1, 1, 7}, {2533, 0, 1, 12}// 28	29	30	
			, {5628, 2, 1, 9}// 31	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hex_StovebigSouthAddonDeed();
			}
		}

		[ Constructable ]
		public hex_StovebigSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 86, -1, 1, 8, 1899, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 82, -1, 1, 10, 1899, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 82, -1, 1, 3, 1899, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1180, -1, 1, 5, 1891, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1180, -1, 1, 12, 1891, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 63, -2, 1, 1, 1899, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 86, -1, 1, 5, 1899, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 82, 0, 1, 3, 1899, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 82, 0, 1, 1, 1899, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 86, 0, 1, 5, 1899, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6571, 0, 1, 8, 0, 0, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 441, -1, 0, 2, 1899, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1180, 0, 1, 5, 1891, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1180, 0, 1, 12, 1891, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 82, 0, 1, 10, 1899, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 86, 0, 1, 8, 1899, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 82, -1, 1, 1, 1899, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6571, -1, 1, 8, 0, 0, "", 1);// 26

		}

		public hex_StovebigSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hex_StovebigSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hex_StovebigSouthAddon();
			}
		}

		[Constructable]
		public hex_StovebigSouthAddonDeed()
		{
			Name = "Big Stove South";
		}

		public hex_StovebigSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}