
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandMushroomEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2476, 1, 0, 5}, {3347, 0, 0, 7}, {3346, -1, 0, 7}// 8	9	10	
					};

 
        private static int[,] m_AddOnComplexComponents = new int[,] {
			  {3348, 1, 0, 7, 1145, -1 }// 11	
		};

    
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandMushroomEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandMushroomEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );

            for (int i = 0; i < m_AddOnComplexComponents.Length / 6; i++)
                AddComplexComponent( m_AddOnComplexComponents[i,0], m_AddOnComplexComponents[i,1], m_AddOnComplexComponents[i,2], m_AddOnComplexComponents[i,3], m_AddOnComplexComponents[i,4], m_AddOnComplexComponents[i,5] );

			AddComplexComponent( 6792, -1, 0, 0, 0, -1, "market stand" );// 1
			AddComplexComponent( 2958, -1, 0, 1, 0, -1, "market stand" );// 2
			AddComplexComponent( 6792, 1, 0, 0, 0, -1, "market stand" );// 3
			AddComplexComponent( 2958, 1, 0, 1, 0, -1, "market stand" );// 4
			AddComplexComponent( 2958, 0, 0, 1, 0, -1, "market stand" );// 5
			AddComplexComponent( 6791, 2, 0, 0, 0, -1, "market stand" );// 6
			AddComplexComponent( 6274, -1, 0, 5, 0, -1, "basket" );// 7
			AddComplexComponent( 3352, 1, 0, 8, 1145, -1, "King Boletus" );// 12

		}

		public MarketStandMushroomEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandMushroomEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandMushroomEastAddon();
			}
		}

		[Constructable]
		public MarketStandMushroomEastAddonDeed()
		{
			Name = "MarketStandMushroomEast";
		}

		public MarketStandMushroomEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}