
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandBeeEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5159, 1, 0, 3}, {5171, 0, 0, 3}, {5167, 0, 0, 3}// 10	11	12	
			, {5175, 0, 0, 3}, {2540, -1, 0, 3}, {5163, 2, 0, 3}// 13	14	15	
			, {5161, 2, 0, 8}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandBeeEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandBeeEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 1448, -1, 0, 5, 542, -1, "market stand" );// 1
			AddComplexComponent( 2958, -1, 0, 1, 542, -1, "market stand" );// 2
			AddComplexComponent( 2958, 1, 0, 1, 542, -1, "market stand" );// 3
			AddComplexComponent( 1448, 0, 0, 5, 542, -1, "market stand" );// 4
			AddComplexComponent( 1448, 1, 0, 5, 542, -1, "market stand" );// 5
			AddComplexComponent( 2958, 0, 0, 1, 542, -1, "market stand" );// 6
			AddComplexComponent( 6791, 2, 0, 0, 542, -1, "market stand" );// 7
			AddComplexComponent( 6792, 1, 0, 0, 542, -1, "market stand" );// 8
			AddComplexComponent( 6792, -1, 0, 0, 542, -1, "market stand" );// 9

		}

		public MarketStandBeeEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandBeeEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandBeeEastAddon();
			}
		}

		[Constructable]
		public MarketStandBeeEastAddonDeed()
		{
			Name = "MarketStandBeeEast";
		}

		public MarketStandBeeEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}