
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandToolEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4136, -1, 0, 7}, {3897, 1, 0, 4}, {4142, 1, 0, 7}// 7	8	9	
			, {4138, 0, 0, 7}, {7864, -1, 0, 7}, {4146, 1, 0, 7}// 10	11	12	
			, {4148, 0, 0, 7}, {4135, 1, 0, 7}, {4140, 0, 0, 3}// 13	14	15	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandToolEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandToolEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6792, 1, 0, 0, 542, -1, "market stand" );// 1
			AddComplexComponent( 6791, 2, 0, 0, 542, -1, "market stand" );// 2
			AddComplexComponent( 2958, 0, 0, 1, 542, -1, "market stand" );// 3
			AddComplexComponent( 6792, -1, 0, 0, 542, -1, "market stand" );// 4
			AddComplexComponent( 2958, 1, 0, 1, 542, -1, "market stand" );// 5
			AddComplexComponent( 2958, -1, 0, 1, 542, -1, "market stand" );// 6

		}

		public MarketStandToolEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandToolEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandToolEastAddon();
			}
		}

		[Constructable]
		public MarketStandToolEastAddonDeed()
		{
			Name = "MarketStandToolEast";
		}

		public MarketStandToolEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}