
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandCopperEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4096, 1, 0, 7}, {4097, 1, 0, 7}, {2498, 1, 0, 7}// 7	8	12	
			, {2547, 0, 0, 7}// 13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandCopperEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandCopperEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6792, 1, 0, 0, 542, -1, "market stand" );// 1
			AddComplexComponent( 2958, 0, 0, 1, 542, -1, "market stand" );// 2
			AddComplexComponent( 6792, -1, 0, 0, 542, -1, "market stand" );// 3
			AddComplexComponent( 2958, 1, 0, 1, 542, -1, "market stand" );// 4
			AddComplexComponent( 2958, -1, 0, 1, 542, -1, "market stand" );// 5
			AddComplexComponent( 2541, -1, 0, 7, 0, -1, "a cauldron" );// 6
			AddComplexComponent( 2529, 1, 0, 8, 0, -1, "small saucer" );// 9
			AddComplexComponent( 2532, 0, 0, 8, 0, -1, "small pot" );// 10
			AddComplexComponent( 2532, 1, 0, 7, 0, -1, "big pot" );// 11

		}

		public MarketStandCopperEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandCopperEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandCopperEastAddon();
			}
		}

		[Constructable]
		public MarketStandCopperEastAddonDeed()
		{
			Name = "MarketStandCopperEast";
		}

		public MarketStandCopperEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}