
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandCheeseEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2430, 1, 0, 7}, {2544, 0, 0, 7}, {2477, 0, 0, 3}// 6	8	9	
			, {2428, 2, 0, 3}, {2429, 2, 0, 2}// 11	13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandCheeseEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandCheeseEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6792, 0, 0, 0, 0, -1, "market stand" );// 1
			AddComplexComponent( 2958, 0, 0, 1, 0, -1, "market stand" );// 2
			AddComplexComponent( 6792, 2, 0, 0, 0, -1, "market stand" );// 3
			AddComplexComponent( 2958, 2, 0, 1, 0, -1, "market stand" );// 4
			AddComplexComponent( 2958, 1, 0, 1, 0, -1, "market stand" );// 5
			AddComplexComponent( 2430, 2, 0, 7, 1153, -1, "sheep cheese" );// 7
			AddComplexComponent( 2429, 1, 0, 3, 1153, -1, "goat cheese" );// 10
			AddComplexComponent( 4090, -1, 0, 0, 1001, -1, "Milk Bucket: (Empty)" );// 12

		}

		public MarketStandCheeseEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandCheeseEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandCheeseEastAddon();
			}
		}

		[Constructable]
		public MarketStandCheeseEastAddonDeed()
		{
			Name = "MarketStandCheeseEast";
		}

		public MarketStandCheeseEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}