
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandHerbsEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2476, 1, 0, 6}, {6479, 0, 0, 6}, {3138, 2, 1, 1}// 8	9	10	
			, {3136, 0, 1, 1}// 11	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandHerbsEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandHerbsEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6792, -1, 0, 0, 542, -1, "market stand" );// 1
            AddComplexComponent(2958, -1, 0, 1, 542, -1, "market stand");// 2
            AddComplexComponent(6792, 1, 0, 0, 542, -1, "market stand");// 3
            AddComplexComponent(2958, 1, 0, 1, 542, -1, "market stand");// 4
            AddComplexComponent(2958, 0, 0, 1, 542, -1, "market stand");// 5
            AddComplexComponent(6791, 2, 0, 0, 542, -1, "market stand");// 6
            AddComplexComponent(6274, -1, 0, 6, 0, -1, "basket");// 7
			AddComplexComponent( 3135, 0, 1, 2, 0, -1, "dried garlic" );// 12
			AddComplexComponent( 3981, 1, 0, 10, 54, -1, "Chamomile" );// 13
			AddComplexComponent( 3976, -1, 0, 8, 1413, -1, "Meadowsweet" );// 14
			AddComplexComponent( 3138, 1, 1, 1, 1429, -1, "Mugwort" );// 15

		}

		public MarketStandHerbsEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandHerbsEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandHerbsEastAddon();
			}
		}

		[Constructable]
		public MarketStandHerbsEastAddonDeed()
		{
			Name = "MarketStandHerbsEast";
		}

		public MarketStandHerbsEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}