/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandFishSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandFishSouthAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandFishSouthAddon()
		{
			AddComponent( new AddonComponent( 2938 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 2509 ), 0, 0, 7 );
			AddComponent( new AddonComponent( 2511 ), 0, 0, 3 );
			AddComponent( new AddonComponent( 2469 ), 0, 0, 8 );
			AddComponent( new AddonComponent( 2938 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 6787 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2426 ), 0, -1, 4 );
			AddComponent( new AddonComponent( 2426 ), 0, -1, 7 );
			AddComponent( new AddonComponent( 2426 ), 0, -1, 8 );
			AddComponent( new AddonComponent( 2426 ), 0, -1, 3 );
			AddComponent( new AddonComponent( 2426 ), 0, -1, 6 );
			AddComponent( new AddonComponent( 6786 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 6787 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2938 ), 0, 1, 1 );
			AddComponent( new AddonComponent( 2508 ), 0, 1, 5 );
			AddComponent( new AddonComponent( 2510 ), 0, 1, 2 );
			AddonComponent ac;
			ac = new AddonComponent( 6786 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6787 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6787 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2508 );
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 2509 );
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 2510 );
			AddComponent( ac, 0, 1, 2 );
			ac = new AddonComponent( 2511 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, -1, 4 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, -1, 7 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, -1, 8 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, -1, 3 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, -1, 6 );
			ac = new AddonComponent( 2469 );
			AddComponent( ac, 0, 0, 8 );

		}

		public MarketStandFishSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandFishSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandFishSouthAddon();
			}
		}

		[Constructable]
		public MarketStandFishSouthAddonDeed()
		{
			Name = "MarketStandFishSouth";
		}

		public MarketStandFishSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}