
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandVegetablesEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3192, -1, 0, 7}, {3192, -1, 0, 8}, {3195, 0, 0, 1}// 7	8	9	
			, {3195, 0, 0, 2}, {3196, 0, 0, 7}, {3181, 1, 0, 7}// 10	11	12	
			, {3182, 1, 0, 8}, {3385, 1, 0, 4}, {3386, 1, 0, 9}// 13	14	15	
			, {3184, 0, 0, 11}, {3174, -1, 0, 4}, {3172, -1, 0, 4}// 16	17	18	
			, {3972, 0, 0, 7}, {3174, -1, 0, 7}, {3192, -1, 0, 7}// 20	21	22	
			, {3191, -1, 0, 3}, {3172, 0, 0, 5}, {3184, 0, 0, 7}// 23	24	25	
			, {3184, 1, 0, 5}, {3386, 0, 0, 7}, {3181, 0, 0, 8}// 26	27	28	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandVegetablesEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandVegetablesEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6792, -1, 0, 0, 0, -1, "market stand" );// 1
			AddComplexComponent( 2958, -1, 0, 1, 0, -1, "market stand" );// 2
			AddComplexComponent( 6792, 1, 0, 0, 0, -1, "market stand" );// 3
			AddComplexComponent( 2958, 1, 0, 1, 0, -1, "market stand" );// 4
			AddComplexComponent( 2958, 0, 0, 1, 0, -1, "market stand" );// 5
			AddComplexComponent( 6791, 2, 0, 0, 0, -1, "market stand" );// 6
			AddComplexComponent( 3135, 0, 1, 0, 0, -1, "dried garlic" );// 19

		}

		public MarketStandVegetablesEastAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandVegetablesEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandVegetablesEastAddon();
			}
		}

		[Constructable]
		public MarketStandVegetablesEastAddonDeed()
		{
			Name = "MarketStandVegetablesEast";
		}

		public MarketStandVegetablesEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}