
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandFurSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4217, 0, -1, 3}, {8967, 0, 1, 3}, {8970, 0, 1, 3}// 9	10	11	
			, {4225, 0, 0, 3}// 12	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandFurSouthAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandFurSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 6787, 0, -1, 0, 0, -1, "market stand" );// 1
			AddComplexComponent( 2938, 0, -1, 1, 0, -1, "market stand" );// 2
			AddComplexComponent( 1445, 0, -1, 5, 0, -1, "market stand" );// 3
			AddComplexComponent( 2938, 0, 0, 1, 0, -1, "market stand" );// 4
			AddComplexComponent( 1445, 0, 0, 5, 0, -1, "market stand" );// 5
			AddComplexComponent( 1445, 0, 1, 5, 0, -1, "market stand" );// 6
			AddComplexComponent( 6787, 0, 1, 0, 0, -1, "market stand" );// 7
			AddComplexComponent( 2938, 0, 1, 1, 0, -1, "market stand" );// 8

		}

		public MarketStandFurSouthAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandFurSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandFurSouthAddon();
			}
		}

		[Constructable]
		public MarketStandFurSouthAddonDeed()
		{
			Name = "MarketStandFurSouth";
		}

		public MarketStandFurSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}