/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandCheeseSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandCheeseSouthAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandCheeseSouthAddon()
		{
			AddComponent( new AddonComponent( 2938 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 2430 ), 0, 0, 7 );
			AddComponent( new AddonComponent( 2429 ), 0, 0, 3 );
			AddComponent( new AddonComponent( 6787 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 2938 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 2430 ), 0, -1, 2 );
			AddComponent( new AddonComponent( 4164 ), 0, -1, 10 );
			AddComponent( new AddonComponent( 6786 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 6787 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 2938 ), 0, 1, 1 );
			AddComponent( new AddonComponent( 2429 ), 0, 1, 2 );
			AddComponent( new AddonComponent( 2544 ), 0, 1, 12 );
			AddComponent( new AddonComponent( 2477 ), 0, 1, 9 );
			AddonComponent ac;
			ac = new AddonComponent( 6787 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6787 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2938 );
			ac.Name = "marketstand";
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6786 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 2429 );
			AddComponent( ac, 0, 1, 2 );
			ac = new AddonComponent( 2430 );
			ac.Hue = 1153;
			ac.Name = "wheel of goat cheese";
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 2429 );
			ac.Hue = 1153;
			ac.Name = "wedge of good goat cheese";
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 2544 );
			AddComponent( ac, 0, 1, 12 );
			ac = new AddonComponent( 4164 );
			ac.Hue = 56;
			ac.Name = "butter";
			AddComponent( ac, 0, -1, 10 );
			ac = new AddonComponent( 2477 );
			ac.Name = "milk";
			AddComponent( ac, 0, 1, 9 );

		}

		public MarketStandCheeseSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandCheeseSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandCheeseSouthAddon();
			}
		}

		[Constructable]
		public MarketStandCheeseSouthAddonDeed()
		{
			Name = "MarketStandCheeseSouth";
		}

		public MarketStandCheeseSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}