
////////////////////////////////////////
//                                    //
//      Generated by CEO's YAAAG      //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandCopperSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2431, 0, 0, 7}, {5344, 0, -1, 7}, {4096, 0, 0, 7}// 6	8	10	
			, {4097, 0, 0, 11}, {2547, 0, 1, 8}, {2553, 0, 0, 7}// 12	14	15	
			, {2553, 0, 1, 9}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandCopperSouthAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandCopperSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( 2938, 0, 0, 1, 542, -1, "market stand" );// 1
			AddComplexComponent( 2938, 0, -1, 1, 542, -1, "market stand" );// 2
			AddComplexComponent( 6787, 0, -1, 0, 542, -1, "market stand" );// 3
			AddComplexComponent( 2938, 0, 1, 1, 542, -1, "market stand" );// 4
			AddComplexComponent( 6787, 0, 1, 0, 542, -1, "market stand" );// 5
			AddComplexComponent( 2541, 0, -1, 7, 0, -1, "a cauldron" );// 7
			AddComplexComponent( 2532, 0, 0, 8, 0, -1, "small pot" );// 9
			AddComplexComponent( 2529, 0, 0, 9, 0, -1, "small saucer" );// 11
			AddComplexComponent( 2532, 0, 0, 7, 0, -1, "big pot" );// 13

		}

		public MarketStandCopperSouthAddon( Serial serial ) : base( serial )
		{
		}

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(item, xoffset, yoffset, zoffset, hue, lightsource, null);
        }

        public void AddComplexComponent(int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandCopperSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandCopperSouthAddon();
			}
		}

		[Constructable]
		public MarketStandCopperSouthAddonDeed()
		{
			Name = "MarketStandCopperSouth";
		}

		public MarketStandCopperSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}