/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketStandFishEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketStandFishEastAddonDeed();
			}
		}

		[ Constructable ]
		public MarketStandFishEastAddon()
		{
			AddComponent( new AddonComponent( 6792 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 2958 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 2508 ), 1, 0, 7 );
			AddComponent( new AddonComponent( 2510 ), 1, 0, 3 );
			AddComponent( new AddonComponent( 2511 ), 1, 0, 4 );
			AddComponent( new AddonComponent( 6791 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 6792 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 2958 ), -1, 0, 1 );
			AddComponent( new AddonComponent( 2426 ), -1, 0, 7 );
			AddComponent( new AddonComponent( 2426 ), -1, 0, 2 );
			AddComponent( new AddonComponent( 2426 ), -1, 0, 5 );
			AddComponent( new AddonComponent( 2508 ), -1, 0, 5 );
			AddComponent( new AddonComponent( 4038 ), -1, 0, 7 );
			AddComponent( new AddonComponent( 2958 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 2509 ), 0, 0, 3 );
			AddComponent( new AddonComponent( 2426 ), 0, 0, 7 );
			AddComponent( new AddonComponent( 2469 ), 0, 0, 9 );
			AddComponent( new AddonComponent( 2509 ), 0, 0, 4 );
			AddComponent( new AddonComponent( 4037 ), 0, 0, 7 );
			AddComponent( new AddonComponent( 4039 ), 0, 0, 7 );
			AddonComponent ac;
			ac = new AddonComponent( 6791 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6792 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6792 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2958 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 2958 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 2958 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 2508 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 2509 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 2510 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 2511 );
			AddComponent( ac, 1, 0, 4 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, -1, 0, 2 );
			ac = new AddonComponent( 2426 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 2469 );
			AddComponent( ac, 0, 0, 9 );
			ac = new AddonComponent( 2509 );
			AddComponent( ac, 0, 0, 4 );
			ac = new AddonComponent( 2508 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 4037 );
			AddComponent( ac, 0, 0, 7 );
			ac = new AddonComponent( 4038 );
			AddComponent( ac, -1, 0, 7 );
			ac = new AddonComponent( 4039 );
			AddComponent( ac, 0, 0, 7 );

		}

		public MarketStandFishEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketStandFishEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketStandFishEastAddon();
			}
		}

		[Constructable]
		public MarketStandFishEastAddonDeed()
		{
			Name = "MarketStandFishEast";
		}

		public MarketStandFishEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}