/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmithWorkShopAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmithWorkShopAddonDeed();
			}
		}

		[ Constructable ]
		public SmithWorkShopAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6534 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 6522 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 6526 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 6531 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 4015 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 7144 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 7150 );
			AddComponent( ac, 2, -3, 2 );
			ac = new AddonComponent( 7156 );
			AddComponent( ac, 2, -3, 4 );
			ac = new AddonComponent( 7162 );
			AddComponent( ac, 2, -3, 6 );
			ac = new AddonComponent( 4020 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 4028 );
			AddComponent( ac, 1, -3, 3 );
			ac = new AddonComponent( 4023 );
			AddComponent( ac, -3, 0, 9 );
			ac = new AddonComponent( 4985 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 4984 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6585 );
			ac.Hue = 1152;
			ac.Name = "Ice Ore";
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 6585 );
			ac.Hue = 1153;
			ac.Name = "Platinum Ore";
			AddComponent( ac, -3, -3, 3 );
			ac = new AddonComponent( 6585 );
			ac.Hue = 1161;
			ac.Name = "Blaze Ore";
			AddComponent( ac, -3, -3, 5 );
			ac = new AddonComponent( 6585 );
			ac.Hue = 1278;
			ac.Name = "Electrum Ore";
			AddComponent( ac, -3, -3, 7 );
			ac = new AddonComponent( 6538 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 6542 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 4016 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 7141 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 7147 );
			AddComponent( ac, -3, 2, 2 );
			ac = new AddonComponent( 7153 );
			AddComponent( ac, -3, 2, 4 );
			ac = new AddonComponent( 7159 );
			AddComponent( ac, -3, 2, 6 );
			ac = new AddonComponent( 4982 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 4983 );
			AddComponent( ac, 1, 3, 0 );

		}

		public SmithWorkShopAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmithWorkShopAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmithWorkShopAddon();
			}
		}

		[Constructable]
		public SmithWorkShopAddonDeed()
		{
			Name = "SmithWorkShop";
		}

		public SmithWorkShopAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}