/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TailorsShopAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TailorsShopAddonDeed();
			}
		}

		[ Constructable ]
		public TailorsShopAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 3782 );
			AddComponent( ac, -3, -3, 6 );
			ac = new AddonComponent( 7618 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 3575 );
			AddComponent( ac, -3, -2, 6 );
			ac = new AddonComponent( 7619 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 7617 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 3997 );
			AddComponent( ac, -3, -1, 4 );
			ac = new AddonComponent( 3999 );
			AddComponent( ac, -3, 0, 7 );
			ac = new AddonComponent( 3613 );
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 4001 );
			ac.Hue = 1152;
			AddComponent( ac, -3, -1, 9 );
			ac = new AddonComponent( 5990 );
			ac.Name = "scraps";
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 3577 );
			AddComponent( ac, -3, 1, 3 );
			ac = new AddonComponent( 4192 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 4191 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 5992 );
			ac.Name = "scraps";
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3990 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 5991 );
			ac.Hue = 1266;
			AddComponent( ac, 1, -3, 1 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 1, -3, 2 );
			ac = new AddonComponent( 5991 );
			ac.Hue = 1153;
			AddComponent( ac, 1, -3, 3 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 1, -3, 4 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 1, -3, 6 );
			ac = new AddonComponent( 2861 );
			AddComponent( ac, 1, -3, 9 );
			ac = new AddonComponent( 5991 );
			ac.Hue = 1161;
			AddComponent( ac, 1, -3, 5 );
			ac = new AddonComponent( 5991 );
			ac.Hue = 33;
			AddComponent( ac, 1, -3, 7 );
			ac = new AddonComponent( 5991 );
			ac.Hue = 2;
			AddComponent( ac, 1, -3, 10 );
			ac = new AddonComponent( 3995 );
			ac.Hue = 121;
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 4011 );
			ac.Hue = 133;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 4127 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 4009 );
			AddComponent( ac, 3, -3, 4 );
			ac = new AddonComponent( 4117 );
			AddComponent( ac, -1, -3, 0 );

		}

		public TailorsShopAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TailorsShopAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TailorsShopAddon();
			}
		}

		[Constructable]
		public TailorsShopAddonDeed()
		{
			Name = "TailorsShop";
		}

		public TailorsShopAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}